[package]
name = "gratex"
version = "0.2.3"
edition = "2021"

[[bin]]
name = "gratex"
test = false
bench = false

[dependencies]
log = "0.4"
fern = "0.5"
chrono = "0.4"
combine = "4.6.6"
structopt = "0.3.26"
structopt-flags = "0.3.6"
anyhow = "1.0.44"
arboard = "3.2.0"
regex = "1.7.3"
