[package]
name = "GraTeX"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
fern = "0.5"
chrono = "0.4"
combine = "4.6.6"
structopt = "0.3.26"
structopt-flags = "0.3.6"
anyhow = "1.0.44"